# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Modified fast CI
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        java:
        - 8
        - 11
        - 17
        - 21
        - 22
      fail-fast: false
      max-parallel: 64
    name: test (${{ matrix.os }}, ${{ matrix.java }})
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test (${{ matrix.os }}, ${{ matrix.java }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/transmittable-thread-local/transmittable-thread-local', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v4
    - run: touch optcd-3.txt
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
        cache: maven
    - run: touch optcd-4.txt
    - name: Build with Maven
      run: ./mvnw -V --no-transfer-progress clean package
    - run: touch optcd-5.txt
    - name: Run unit test under ttl agent, include check for ExecutorService, ForkJoinPool,
        Timer/TimerTask
      working-directory: ttl2-compatible
      run: |-
        ../mvnw -V --no-transfer-progress -Penable-ttl-agent-for-test surefire:test '-Dttl.agent.extra.d.options=-Drun-ttl-test-under-agent-with-enable-timer-task=true'
    - run: touch optcd-6.txt
    - name: Run unit test under ttl agent, and turn on the disable inheritable for
        thread pool enhancement
      working-directory: ttl2-compatible
      run: |-
        ../mvnw -V --no-transfer-progress -Penable-ttl-agent-for-test surefire:test '-Dttl.agent.extra.args=ttl.agent.disable.inheritable.for.thread.pool:true' '-Dttl.agent.extra.d.options=-Drun-ttl-test-under-agent-with-disable-inheritable=true'
    - run: touch optcd-7.txt
    - name: Run agent check for Timer/TimerTask, explicit "ttl.agent.enable.timer.task"
      working-directory: ttl2-compatible
      run: |-
        ../mvnw -V --no-transfer-progress -Penable-ttl-agent-for-test surefire:test '-Dttl.agent.extra.args=ttl.agent.enable.timer.task:true' '-Dttl.agent.extra.d.options=-Drun-ttl-test-under-agent-with-enable-timer-task=true'
    - run: touch optcd-8.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test (${{ matrix.os }}, ${{ matrix.java }})
        path: /home/runner/inotifywait-log-test (${{ matrix.os }}, ${{ matrix.java
          }}).csv
'on':
- push
- workflow_dispatch
